server:
  port: 8288
---
spring:
  application:
    name: AdminService

---
logging:
  level:
    com.hocmai.backend: debug
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/my_pets
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 10
  second-datasource:
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 10
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
        show-sql: false
  flyway:
    enabled: true
    locations:
      - classpath:migration

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000 # 60 minutes duration by default: 60 minutes * 60 seconds * 1000 miliseconds
